import type {
  ComponentNode,
  ExpressionNode,
  FastFunctionNode,
  ImportNode,
  ProgramNode,
  RenderSegmentNode,
  StatementNode,
} from "./ast";

export interface EmitResult {
  code: string;
}

export function emitJavaScript(program: ProgramNode): EmitResult {
  const lines: string[] = [];
  lines.push("// Generated by Velox v0.18");
  lines.push("");

  const imports = program.body.filter((node): node is ImportNode => node.kind === "Import");
  const nonImports = program.body.filter((node): node is Exclude<StatementNode, ImportNode> => node.kind !== "Import");
  for (const importNode of imports) {
    lines.push(emitImport(importNode));
  }
  if (imports.length > 0) {
    lines.push("");
  }

  const hasComponent = nonImports.some((node) => node.kind === "Component");
  if (hasComponent) {
    lines.push(REACTIVE_RUNTIME);
    lines.push("");
  }

  for (const node of nonImports) {
    lines.push(emitStatement(node));
    lines.push("");
  }

  return { code: lines.join("\n").trim() + "\n" };
}

function emitStatement(node: StatementNode): string {
  if (node.kind === "Import") {
    return emitImport(node);
  }
  if (node.kind === "Component") {
    return emitComponent(node);
  }
  return emitFastFunction(node);
}

function emitImport(node: ImportNode): string {
  const source = rewriteImportSpecifier(node.source);
  if (node.sideEffectOnly) {
    return `import ${JSON.stringify(source)};`;
  }

  const parts: string[] = [];
  if (node.defaultImport) {
    parts.push(node.defaultImport);
  }
  if (node.namespaceImport) {
    parts.push(`* as ${node.namespaceImport}`);
  } else if (node.namedImports.length > 0) {
    const named = node.namedImports
      .map((entry) => (entry.imported === entry.local ? entry.imported : `${entry.imported} as ${entry.local}`))
      .join(", ");
    parts.push(`{ ${named} }`);
  }
  if (parts.length === 0) {
    throw new Error(`Invalid import from "${node.source}".`);
  }
  return `import ${parts.join(", ")} from ${JSON.stringify(source)};`;
}

function rewriteImportSpecifier(source: string): string {
  if (hasVxExtension(source)) {
    return source.slice(0, -3) + ".js";
  }
  if ((source.startsWith("./") || source.startsWith("../")) && !hasKnownExtension(source)) {
    return `${source}.js`;
  }
  return source;
}

function hasVxExtension(source: string): boolean {
  return source.toLowerCase().endsWith(".vx");
}

function hasKnownExtension(spec: string): boolean {
  const slash = Math.max(spec.lastIndexOf("/"), spec.lastIndexOf("\\"));
  const base = slash === -1 ? spec : spec.slice(slash + 1);
  const dot = base.lastIndexOf(".");
  return dot > 0;
}

function emitComponent(node: ComponentNode): string {
  const lines: string[] = [];
  const args = node.params.map((p) => p.name).join(", ");
  const paramNames = node.params.map((p) => p.name);
  const scopeNames = new Set<string>([...paramNames, ...node.state.map((s) => s.name)]);
  const stateLiteral = node.state.map((decl) => `    ${decl.name}: ${emitExpression(decl.value)},`).join("\n");
  const scopeMap = new Map<string, string>();
  for (const name of scopeNames) {
    scopeMap.set(name, `__ctx.${name}`);
  }
  const templateExpr = compileTemplateExpression(node.render.segments, scopeMap);
  for (const eventBinding of node.render.events) {
    if (!scopeMap.has(eventBinding.handler)) {
      throw new Error(
        `Unknown event handler "${eventBinding.handler}" for on:${eventBinding.event}. ` +
          "Declare it as a component param or ~state function.",
      );
    }
  }
  const eventListLiteral = JSON.stringify(node.render.events);

  lines.push(`export function ${node.name}(${args}) {`);
  lines.push(`  const __params = { ${paramNames.join(", ")} };`);
  lines.push("  const __reactive = __veloxCreateReactiveState({");
  lines.push(stateLiteral || "    // no local state");
  lines.push("  });");
  lines.push("  const state = __reactive.state;");
  lines.push("");
  lines.push("  const render = () => {");
  lines.push("    const __ctx = { ...__params, ...state };");
  lines.push(`    return ${templateExpr};`);
  lines.push("  };");
  lines.push("  const events = " + eventListLiteral + ";");
  lines.push("");
  lines.push("  const mount = (target) => {");
  lines.push("    if (!(target instanceof Element)) {");
  lines.push('      throw new Error("Velox mount(target): target must be a DOM Element");');
  lines.push("    }");
  lines.push("    target.innerHTML = render();");
  lines.push("    __veloxBindEvents(target, events, __params, state);");
  lines.push("    const unsubscribe = __reactive.subscribe(() => {");
  lines.push("      target.innerHTML = render();");
  lines.push("      __veloxBindEvents(target, events, __params, state);");
  lines.push("    });");
  lines.push("    return () => unsubscribe();");
  lines.push("  };");
  lines.push("");
  lines.push("  return {");
  lines.push("    state,");
  lines.push("    render,");
  lines.push("    events,");
  lines.push("    mount,");
  lines.push("    subscribe: __reactive.subscribe,");
  lines.push("    set: __reactive.set,");
  lines.push("  };");
  lines.push("}");

  return lines.join("\n");
}

function emitFastFunction(node: FastFunctionNode): string {
  const args = node.params.map((p) => p.name).join(", ");
  const wasmBytes = generateFastWasmBytes(node);
  const bytesLiteral = wasmBytes.join(", ");
  const lines: string[] = [];

  lines.push(`const __velox_wasm_${node.name}_bytes = new Uint8Array([${bytesLiteral}]);`);
  lines.push(
    `const __velox_wasm_${node.name}_instance = new WebAssembly.Instance(` +
      `new WebAssembly.Module(__velox_wasm_${node.name}_bytes), {}`,
  );
  lines.push(");");
  lines.push(`const __velox_wasm_${node.name}_fn = __velox_wasm_${node.name}_instance.exports.${node.name};`);
  lines.push(`export function ${node.name}(${args}) {`);
  lines.push(`  return __velox_wasm_${node.name}_fn(${args});`);
  lines.push("}");

  return lines.join("\n");
}

function compileTemplateExpression(
  segments: RenderSegmentNode[],
  scopeMap: Map<string, string>,
): string {
  const out: string[] = [];
  for (const segment of segments) {
    if (segment.kind === "RenderText") {
      out.push(JSON.stringify(segment.value));
      continue;
    }
    if (segment.kind === "RenderBinding") {
      const bindingExpr = scopeMap.get(segment.name);
      if (!bindingExpr) {
        throw new Error(`Unknown render binding "{${segment.name}}". Declare it as a param or ~state.`);
      }
      out.push(`String(${bindingExpr})`);
      continue;
    }
    if (segment.kind === "RenderIf") {
      const conditionExpr = compileRenderConditionExpression(segment.condition, scopeMap);
      const truthy = compileTemplateExpression(segment.consequent, scopeMap);
      const falsy = segment.alternate ? compileTemplateExpression(segment.alternate, scopeMap) : '""';
      out.push(`(${conditionExpr} ? (${truthy}) : (${falsy}))`);
      continue;
    }

    const sourceExpr = scopeMap.get(segment.source);
    if (!sourceExpr) {
      throw new Error(
        `Unknown render each source "{#each ${segment.source} as ${segment.item}}". Declare it as a param or ~state.`,
      );
    }

    const loopVar = "__velox_item";
    const indexVar = "__velox_index";
    const loopScope = new Map(scopeMap);
    loopScope.set(segment.item, loopVar);
    if (segment.index) {
      loopScope.set(segment.index, indexVar);
    }
    const bodyExpr = compileTemplateExpression(segment.body, loopScope);
    out.push(
      `(Array.isArray(${sourceExpr}) ? ${sourceExpr}.map((${loopVar}, ${indexVar}) => (${bodyExpr})).join("") : "")`,
    );
  }
  return out.length > 0 ? out.join(" + ") : '""';
}

function emitExpression(expr: ExpressionNode): string {
  switch (expr.kind) {
    case "NumberLiteral":
      return String(expr.value);
    case "StringLiteral":
      return JSON.stringify(expr.value);
    case "BooleanLiteral":
      return expr.value ? "true" : "false";
    case "ArrayLiteral":
      return `[${expr.elements.map((el) => emitExpression(el)).join(", ")}]`;
    case "ObjectLiteral":
      return `{ ${expr.properties.map((prop) => `${JSON.stringify(prop.key)}: ${emitExpression(prop.value)}`).join(", ")} }`;
    case "Identifier":
      return expr.name;
    case "MemberExpression":
      if (!expr.computed && expr.property.kind === "Identifier") {
        return `(${emitExpression(expr.object)}.${expr.property.name})`;
      }
      return `(${emitExpression(expr.object)}[${emitExpression(expr.property)}])`;
    case "UnaryExpression":
      return `(${expr.operator}${emitExpression(expr.argument)})`;
    case "BinaryExpression":
      return `(${emitExpression(expr.left)} ${expr.operator} ${emitExpression(expr.right)})`;
    case "CallExpression":
      return `${emitExpression(expr.callee)}(${expr.args.map((arg) => emitExpression(arg)).join(", ")})`;
  }
}

function generateFastWasmBytes(node: FastFunctionNode): number[] {
  for (const param of node.params) {
    if (param.type !== "i32") {
      throw new Error(`@fast currently supports only i32 params. Found ${param.type} in ${node.name}`);
    }
  }
  if (node.returnType !== "i32") {
    throw new Error(`@fast currently supports only i32 return type. Found ${node.returnType} in ${node.name}`);
  }

  const compiled = compileFastBody(node);

  const bytes: number[] = [];
  bytes.push(0x00, 0x61, 0x73, 0x6d);
  bytes.push(0x01, 0x00, 0x00, 0x00);

  const typePayload = [0x01, 0x60, ...encodeU32(node.params.length), ...repeatByte(0x7f, node.params.length), 0x01, 0x7f];
  bytes.push(...makeSection(1, typePayload));

  const functionPayload = [0x01, 0x00];
  bytes.push(...makeSection(3, functionPayload));

  const nameBytes = toUtf8Bytes(node.name);
  const exportPayload = [0x01, ...encodeU32(nameBytes.length), ...nameBytes, 0x00, 0x00];
  bytes.push(...makeSection(7, exportPayload));

  const localDecls =
    compiled.localCount > 0 ? [0x01, ...encodeU32(compiled.localCount), 0x7f] : [0x00];
  const funcBody = [...localDecls, ...compiled.instructions, 0x0b];
  const codePayload = [0x01, ...encodeU32(funcBody.length), ...funcBody];
  bytes.push(...makeSection(10, codePayload));

  return bytes;
}

interface CompiledFastBody {
  instructions: number[];
  localCount: number;
}

function compileFastBody(node: FastFunctionNode): CompiledFastBody {
  const statements = parseFastStatements(node.body);
  if (statements.length === 0) {
    throw new Error(`@fast function "${node.name}" has an empty body.`);
  }

  const scope = new Map<string, number>();
  for (let i = 0; i < node.params.length; i++) {
    scope.set(node.params[i].name, i);
  }

  const instructions: number[] = [];
  const allocator: FastLocalAllocator = { paramCount: node.params.length, localCount: 0 };

  for (let i = 0; i < statements.length; i++) {
    const stmt = statements[i];
    const isLast = i === statements.length - 1;

    if (stmt.kind === "let") {
      const localIndex = allocateFastLocal(scope, stmt.name, allocator, node.name);
      instructions.push(...compileFastExpression(stmt.expr, scope, node.name));
      instructions.push(0x21, ...encodeU32(localIndex));
      if (isLast) {
        throw new Error(`@fast "${node.name}" ends with let statement. End with expression or return.`);
      }
      continue;
    }

    if (stmt.kind === "assign") {
      const localIndex = scope.get(stmt.name);
      if (localIndex === undefined) {
        throw new Error(`Unknown @fast identifier "${stmt.name}" in ${node.name}`);
      }
      instructions.push(...compileFastExpression(stmt.expr, scope, node.name));
      instructions.push(0x21, ...encodeU32(localIndex));
      if (isLast) {
        throw new Error(`@fast "${node.name}" ends with assignment. End with expression or return.`);
      }
      continue;
    }

    if (stmt.kind === "return") {
      instructions.push(...compileFastExpression(stmt.expr, scope, node.name));
      instructions.push(0x0f);
      if (!isLast) {
        throw new Error(`@fast "${node.name}" has statements after return.`);
      }
      continue;
    }

    if (stmt.kind === "if") {
      const compiledIf = compileFastIfStatement(stmt, scope, allocator, node.name);
      instructions.push(...compiledIf.instructions);
      if (compiledIf.alwaysReturns) {
        if (!isLast) {
          throw new Error(`@fast "${node.name}" has statements after return.`);
        }
        // Keep function validation stable even when control-flow always returns in branches.
        instructions.push(0x41, ...encodeI32(0));
        continue;
      }
      if (isLast) {
        throw new Error(`@fast "${node.name}" ends with if without guaranteed return.`);
      }
      continue;
    }

    if (stmt.kind === "while") {
      instructions.push(...compileFastWhileStatement(stmt, scope, allocator, node.name));
      if (isLast) {
        throw new Error(`@fast "${node.name}" ends with while without guaranteed return.`);
      }
      continue;
    }

    instructions.push(...compileFastExpression(stmt.expr, scope, node.name));
    if (!isLast) {
      instructions.push(0x1a);
    }
  }

  return { instructions, localCount: allocator.localCount };
}

type FastStatement =
  | { kind: "let"; name: string; expr: string }
  | { kind: "assign"; name: string; expr: string }
  | { kind: "return"; expr: string }
  | { kind: "if"; condition: string; thenBranch: FastStatement[]; elseBranch: FastStatement[] | null }
  | { kind: "while"; condition: string; body: FastStatement[] }
  | { kind: "expr"; expr: string };

function parseFastStatements(body: string): FastStatement[] {
  const chunks = splitTopLevelStatements(body);
  return chunks.map(parseFastStatement);
}

function splitTopLevelStatements(body: string): string[] {
  const src = body.replace(/\r/g, "");
  const chunks: string[] = [];
  let braceDepth = 0;
  let parenDepth = 0;
  let current = "";

  for (let i = 0; i < src.length; i++) {
    const ch = src[i];
    if (ch === "{") {
      braceDepth++;
      current += ch;
      continue;
    }
    if (ch === "}") {
      braceDepth--;
      current += ch;
      continue;
    }
    if (ch === "(") {
      parenDepth++;
      current += ch;
      continue;
    }
    if (ch === ")") {
      parenDepth--;
      current += ch;
      continue;
    }

    if ((ch === "\n" || ch === ";") && braceDepth === 0 && parenDepth === 0) {
      const trimmed = current.trim();
      if (trimmed.length > 0) {
        chunks.push(trimmed);
      }
      current = "";
      continue;
    }

    current += ch;
  }

  const tail = current.trim();
  if (tail.length > 0) {
    chunks.push(tail);
  }
  return chunks;
}

function parseFastStatement(line: string): FastStatement {
  const letMatch = line.match(/^let\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([\s\S]+)$/);
  if (letMatch) {
    return { kind: "let", name: letMatch[1], expr: letMatch[2].trim() };
  }

  const returnMatch = line.match(/^return\s+([\s\S]+)$/);
  if (returnMatch) {
    return { kind: "return", expr: returnMatch[1].trim() };
  }

  if (line.startsWith("if ")) {
    return parseFastIfStatement(line);
  }
  if (line.startsWith("while ")) {
    return parseFastWhileStatement(line);
  }
  const assign = tryParseFastAssignment(line);
  if (assign) {
    return { kind: "assign", name: assign.name, expr: assign.expr };
  }

  return { kind: "expr", expr: line };
}

function tryParseFastAssignment(line: string): { name: string; expr: string } | null {
  let parenDepth = 0;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === "(") {
      parenDepth++;
      continue;
    }
    if (ch === ")") {
      parenDepth--;
      continue;
    }
    if (ch !== "=" || parenDepth !== 0) {
      continue;
    }
    const prev = i > 0 ? line[i - 1] : "";
    const next = i + 1 < line.length ? line[i + 1] : "";
    if (prev === "=" || next === "=") {
      continue;
    }
    const lhs = line.slice(0, i).trim();
    const rhs = line.slice(i + 1).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(lhs) || rhs.length === 0) {
      return null;
    }
    return { name: lhs, expr: rhs };
  }
  return null;
}

function parseFastIfStatement(line: string): FastStatement {
  let i = 2;
  while (i < line.length && /\s/.test(line[i])) {
    i++;
  }

  let parenDepth = 0;
  let openBrace = -1;
  for (let j = i; j < line.length; j++) {
    const ch = line[j];
    if (ch === "(") {
      parenDepth++;
    } else if (ch === ")") {
      parenDepth--;
    } else if (ch === "{" && parenDepth === 0) {
      openBrace = j;
      break;
    }
  }

  if (openBrace === -1) {
    throw new Error(`Invalid @fast if statement "${line}". Missing '{'.`);
  }

  const condition = line.slice(i, openBrace).trim();
  if (condition.length === 0) {
    throw new Error(`Invalid @fast if statement "${line}". Missing condition.`);
  }

  const firstBlock = extractBraceBlock(line, openBrace);
  const thenBody = firstBlock.body.trim();
  const thenBranch = parseFastStatements(thenBody);

  const rest = line.slice(firstBlock.end + 1).trim();
  if (rest.length === 0) {
    return { kind: "if", condition, thenBranch, elseBranch: null };
  }

  if (!rest.startsWith("else")) {
    throw new Error(`Invalid @fast if statement "${line}". Expected else block.`);
  }

  const afterElse = rest.slice(4).trim();
  if (!afterElse.startsWith("{")) {
    throw new Error(`Invalid @fast if statement "${line}". Expected '{' after else.`);
  }

  const secondBlock = extractBraceBlock(afterElse, 0);
  const trailing = afterElse.slice(secondBlock.end + 1).trim();
  if (trailing.length > 0) {
    throw new Error(`Invalid @fast if statement "${line}". Unexpected trailing tokens.`);
  }

  const elseBranch = parseFastStatements(secondBlock.body.trim());
  return { kind: "if", condition, thenBranch, elseBranch };
}

function parseFastWhileStatement(line: string): FastStatement {
  let i = 5;
  while (i < line.length && /\s/.test(line[i])) {
    i++;
  }

  let parenDepth = 0;
  let openBrace = -1;
  for (let j = i; j < line.length; j++) {
    const ch = line[j];
    if (ch === "(") {
      parenDepth++;
    } else if (ch === ")") {
      parenDepth--;
    } else if (ch === "{" && parenDepth === 0) {
      openBrace = j;
      break;
    }
  }

  if (openBrace === -1) {
    throw new Error(`Invalid @fast while statement "${line}". Missing '{'.`);
  }

  const condition = line.slice(i, openBrace).trim();
  if (condition.length === 0) {
    throw new Error(`Invalid @fast while statement "${line}". Missing condition.`);
  }

  const block = extractBraceBlock(line, openBrace);
  const trailing = line.slice(block.end + 1).trim();
  if (trailing.length > 0) {
    throw new Error(`Invalid @fast while statement "${line}". Unexpected trailing tokens.`);
  }

  return { kind: "while", condition, body: parseFastStatements(block.body.trim()) };
}

function extractBraceBlock(src: string, openBraceIndex: number): { body: string; end: number } {
  let depth = 0;
  let end = -1;
  for (let i = openBraceIndex; i < src.length; i++) {
    const ch = src[i];
    if (ch === "{") {
      depth++;
    } else if (ch === "}") {
      depth--;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }
  if (end === -1) {
    throw new Error(`Unterminated @fast block in "${src}"`);
  }
  return { body: src.slice(openBraceIndex + 1, end), end };
}

interface CompiledFastIf {
  instructions: number[];
  alwaysReturns: boolean;
}

interface FastLocalAllocator {
  paramCount: number;
  localCount: number;
}

function allocateFastLocal(
  scope: Map<string, number>,
  name: string,
  allocator: FastLocalAllocator,
  functionName: string,
): number {
  if (scope.has(name)) {
    throw new Error(`Duplicate @fast name "${name}" in ${functionName}`);
  }
  const index = allocator.paramCount + allocator.localCount;
  allocator.localCount++;
  scope.set(name, index);
  return index;
}

function compileFastIfStatement(
  stmt: Extract<FastStatement, { kind: "if" }>,
  scope: Map<string, number>,
  allocator: FastLocalAllocator,
  functionName: string,
): CompiledFastIf {
  const cond = compileFastExpression(stmt.condition, scope, functionName);
  const thenCompiled = compileFastBranch(stmt.thenBranch, scope, allocator, functionName);
  const elseCompiled = stmt.elseBranch
    ? compileFastBranch(stmt.elseBranch, scope, allocator, functionName)
    : { instructions: [], alwaysReturns: false };

  const instructions: number[] = [...cond, 0x04, 0x40, ...thenCompiled.instructions];
  if (stmt.elseBranch) {
    instructions.push(0x05, ...elseCompiled.instructions);
  }
  instructions.push(0x0b);

  return {
    instructions,
    alwaysReturns: thenCompiled.alwaysReturns && (stmt.elseBranch ? elseCompiled.alwaysReturns : false),
  };
}

function compileFastWhileStatement(
  stmt: Extract<FastStatement, { kind: "while" }>,
  scope: Map<string, number>,
  allocator: FastLocalAllocator,
  functionName: string,
): number[] {
  const bodyCompiled = compileFastBranch(stmt.body, scope, allocator, functionName);
  const cond = compileFastExpression(stmt.condition, scope, functionName);
  return [
    0x02,
    0x40,
    0x03,
    0x40,
    ...cond,
    0x45,
    0x0d,
    ...encodeU32(1),
    ...bodyCompiled.instructions,
    0x0c,
    ...encodeU32(0),
    0x0b,
    0x0b,
  ];
}

function compileFastBranch(
  statements: FastStatement[],
  parentScope: Map<string, number>,
  allocator: FastLocalAllocator,
  functionName: string,
): { instructions: number[]; alwaysReturns: boolean } {
  const scope = new Map(parentScope);
  const instructions: number[] = [];

  for (let i = 0; i < statements.length; i++) {
    const stmt = statements[i];
    const isLast = i === statements.length - 1;

    if (stmt.kind === "let") {
      const localIndex = allocateFastLocal(scope, stmt.name, allocator, functionName);
      instructions.push(...compileFastExpression(stmt.expr, scope, functionName));
      instructions.push(0x21, ...encodeU32(localIndex));
      if (isLast) {
        return { instructions, alwaysReturns: false };
      }
      continue;
    }

    if (stmt.kind === "assign") {
      const localIndex = scope.get(stmt.name);
      if (localIndex === undefined) {
        throw new Error(`Unknown @fast identifier "${stmt.name}" in ${functionName}`);
      }
      instructions.push(...compileFastExpression(stmt.expr, scope, functionName));
      instructions.push(0x21, ...encodeU32(localIndex));
      if (isLast) {
        return { instructions, alwaysReturns: false };
      }
      continue;
    }

    if (stmt.kind === "return") {
      instructions.push(...compileFastExpression(stmt.expr, scope, functionName), 0x0f);
      if (!isLast) {
        throw new Error(`@fast "${functionName}" has statements after return.`);
      }
      return { instructions, alwaysReturns: true };
    }

    if (stmt.kind === "if") {
      const compiledIf = compileFastIfStatement(stmt, scope, allocator, functionName);
      instructions.push(...compiledIf.instructions);
      if (compiledIf.alwaysReturns) {
        if (!isLast) {
          throw new Error(`@fast "${functionName}" has statements after return.`);
        }
        return { instructions, alwaysReturns: true };
      }
      if (isLast) {
        return { instructions, alwaysReturns: false };
      }
      continue;
    }

    if (stmt.kind === "while") {
      instructions.push(...compileFastWhileStatement(stmt, scope, allocator, functionName));
      if (isLast) {
        return { instructions, alwaysReturns: false };
      }
      continue;
    }

    instructions.push(...compileFastExpression(stmt.expr, scope, functionName));
    instructions.push(0x1a);
  }

  return { instructions, alwaysReturns: false };
}

type FastExprTokenType = "number" | "identifier" | "symbol" | "eof";

interface FastExprToken {
  type: FastExprTokenType;
  value: string;
}

function compileFastExpression(
  expr: string,
  scope: Map<string, number>,
  functionName: string,
): number[] {
  const tokens = tokenizeFastExpr(expr);
  const parser = new FastExprCompiler(tokens, scope, functionName);
  return parser.compile();
}

function tokenizeFastExpr(expr: string): FastExprToken[] {
  const tokens: FastExprToken[] = [];
  let i = 0;
  while (i < expr.length) {
    const ch = expr[i];
    if (/\s/.test(ch)) {
      i++;
      continue;
    }
    if (/[0-9]/.test(ch)) {
      let value = ch;
      i++;
      while (i < expr.length && /[0-9]/.test(expr[i])) {
        value += expr[i];
        i++;
      }
      tokens.push({ type: "number", value });
      continue;
    }
    if (/[A-Za-z_]/.test(ch)) {
      let value = ch;
      i++;
      while (i < expr.length && /[A-Za-z0-9_]/.test(expr[i])) {
        value += expr[i];
        i++;
      }
      tokens.push({ type: "identifier", value });
      continue;
    }

    const two = expr.slice(i, i + 2);
    if (["==", "!=", "<=", ">=", "&&", "||"].includes(two)) {
      tokens.push({ type: "symbol", value: two });
      i += 2;
      continue;
    }

    if ("+-*/%()<>".includes(ch)) {
      tokens.push({ type: "symbol", value: ch });
      i++;
      continue;
    }
    throw new Error(`Unsupported @fast character "${ch}" in expression "${expr}"`);
  }
  tokens.push({ type: "eof", value: "" });
  return tokens;
}

class FastExprCompiler {
  private readonly tokens: FastExprToken[];
  private readonly scope: Map<string, number>;
  private readonly functionName: string;
  private current = 0;

  constructor(tokens: FastExprToken[], scope: Map<string, number>, functionName: string) {
    this.tokens = tokens;
    this.scope = scope;
    this.functionName = functionName;
  }

  compile(): number[] {
    const code = this.parseLogicalOr();
    if (!this.check("eof")) {
      throw new Error(`Unexpected token "${this.peek().value}" in @fast ${this.functionName}`);
    }
    return code;
  }

  private parseLogicalOr(): number[] {
    let code = this.parseLogicalAnd();
    while (this.matchSymbol("||")) {
      const rhs = this.parseLogicalAnd();
      code = [...code, ...rhs, opToOpcode("||")];
    }
    return code;
  }

  private parseLogicalAnd(): number[] {
    let code = this.parseEquality();
    while (this.matchSymbol("&&")) {
      const rhs = this.parseEquality();
      code = [...code, ...rhs, opToOpcode("&&")];
    }
    return code;
  }

  private parseEquality(): number[] {
    let code = this.parseComparison();
    while (this.matchSymbol("==") || this.matchSymbol("!=")) {
      const op = this.previous().value;
      const rhs = this.parseComparison();
      code = [...code, ...rhs, opToOpcode(op)];
    }
    return code;
  }

  private parseComparison(): number[] {
    let code = this.parseAddSub();
    while (
      this.matchSymbol("<") ||
      this.matchSymbol(">") ||
      this.matchSymbol("<=") ||
      this.matchSymbol(">=")
    ) {
      const op = this.previous().value;
      const rhs = this.parseAddSub();
      code = [...code, ...rhs, opToOpcode(op)];
    }
    return code;
  }

  private parseAddSub(): number[] {
    let code = this.parseMulDiv();
    while (this.matchSymbol("+") || this.matchSymbol("-")) {
      const op = this.previous().value;
      const rhs = this.parseMulDiv();
      code = [...code, ...rhs, opToOpcode(op)];
    }
    return code;
  }

  private parseMulDiv(): number[] {
    let code = this.parseUnary();
    while (this.matchSymbol("*") || this.matchSymbol("/") || this.matchSymbol("%")) {
      const op = this.previous().value;
      const rhs = this.parseUnary();
      code = [...code, ...rhs, opToOpcode(op)];
    }
    return code;
  }

  private parseUnary(): number[] {
    if (this.matchSymbol("-")) {
      const rhs = this.parseUnary();
      return [0x41, ...encodeI32(0), ...rhs, 0x6b];
    }
    return this.parsePrimary();
  }

  private parsePrimary(): number[] {
    if (this.matchType("number")) {
      return [0x41, ...encodeI32(Number(this.previous().value))];
    }

    if (this.matchType("identifier")) {
      const name = this.previous().value;
      const index = this.scope.get(name);
      if (index === undefined) {
        throw new Error(`Unknown @fast identifier "${name}" in ${this.functionName}`);
      }
      return [0x20, ...encodeU32(index)];
    }

      if (this.matchSymbol("(")) {
        const inner = this.parseLogicalOr();
        this.consumeSymbol(")");
        return inner;
      }

    throw new Error(`Invalid @fast expression near "${this.peek().value}" in ${this.functionName}`);
  }

  private matchType(type: FastExprTokenType): boolean {
    if (this.check(type)) {
      this.advance();
      return true;
    }
    return false;
  }

  private matchSymbol(symbol: string): boolean {
    if (this.peek().type === "symbol" && this.peek().value === symbol) {
      this.advance();
      return true;
    }
    return false;
  }

  private consumeSymbol(symbol: string): void {
    if (!this.matchSymbol(symbol)) {
      throw new Error(`Expected "${symbol}" in @fast ${this.functionName}`);
    }
  }

  private check(type: FastExprTokenType): boolean {
    return this.peek().type === type;
  }

  private advance(): FastExprToken {
    if (!this.check("eof")) {
      this.current++;
    }
    return this.previous();
  }

  private peek(): FastExprToken {
    return this.tokens[this.current];
  }

  private previous(): FastExprToken {
    return this.tokens[this.current - 1];
  }
}

function opToOpcode(op: string): number {
  switch (op) {
    case "+":
      return 0x6a;
    case "-":
      return 0x6b;
    case "*":
      return 0x6c;
    case "/":
      return 0x6d;
    case "%":
      return 0x6f;
    case "==":
      return 0x46;
    case "!=":
      return 0x47;
    case "<":
      return 0x48;
    case ">":
      return 0x4a;
    case "<=":
      return 0x4c;
    case ">=":
      return 0x4e;
    case "&&":
      return 0x71;
    case "||":
      return 0x72;
    default:
      throw new Error(`Unsupported @fast operator: ${op}`);
  }
}

function makeSection(id: number, payload: number[]): number[] {
  return [id, ...encodeU32(payload.length), ...payload];
}

function encodeU32(value: number): number[] {
  const out: number[] = [];
  let v = value >>> 0;
  do {
    let byte = v & 0x7f;
    v >>>= 7;
    if (v !== 0) {
      byte |= 0x80;
    }
    out.push(byte);
  } while (v !== 0);
  return out;
}

function encodeI32(value: number): number[] {
  const out: number[] = [];
  let v = value | 0;
  let more = true;

  while (more) {
    let byte = v & 0x7f;
    v >>= 7;
    const signBit = byte & 0x40;
    if ((v === 0 && signBit === 0) || (v === -1 && signBit !== 0)) {
      more = false;
    } else {
      byte |= 0x80;
    }
    out.push(byte);
  }

  return out;
}

function repeatByte(byte: number, count: number): number[] {
  return Array.from({ length: count }, () => byte);
}

function toUtf8Bytes(value: string): number[] {
  return [...Buffer.from(value, "utf8")];
}

type RenderCondTokenType = "number" | "identifier" | "bool" | "symbol" | "eof";

interface RenderCondToken {
  type: RenderCondTokenType;
  value: string;
}

function compileRenderConditionExpression(
  condition: string,
  scopeMap: Map<string, string>,
): string {
  const tokens = tokenizeRenderCondition(condition);
  const parser = new RenderConditionCompiler(tokens, scopeMap, condition);
  return parser.compile();
}

function tokenizeRenderCondition(condition: string): RenderCondToken[] {
  const tokens: RenderCondToken[] = [];
  let i = 0;
  while (i < condition.length) {
    const ch = condition[i];
    if (/\s/.test(ch)) {
      i++;
      continue;
    }

    const two = condition.slice(i, i + 2);
    if (["&&", "||", "==", "!=", "<=", ">="].includes(two)) {
      tokens.push({ type: "symbol", value: two });
      i += 2;
      continue;
    }

    if ("()+-*/!<>.[]".includes(ch)) {
      tokens.push({ type: "symbol", value: ch });
      i++;
      continue;
    }

    if (/[0-9]/.test(ch)) {
      let value = ch;
      i++;
      while (i < condition.length && /[0-9]/.test(condition[i])) {
        value += condition[i];
        i++;
      }
      tokens.push({ type: "number", value });
      continue;
    }

    if (/[A-Za-z_]/.test(ch)) {
      let value = ch;
      i++;
      while (i < condition.length && /[A-Za-z0-9_]/.test(condition[i])) {
        value += condition[i];
        i++;
      }
      if (value === "true" || value === "false") {
        tokens.push({ type: "bool", value });
      } else {
        tokens.push({ type: "identifier", value });
      }
      continue;
    }

    throw new Error(`Invalid token "${ch}" in render condition "${condition}"`);
  }
  tokens.push({ type: "eof", value: "" });
  return tokens;
}

class RenderConditionCompiler {
  private readonly tokens: RenderCondToken[];
  private readonly scopeMap: Map<string, string>;
  private readonly source: string;
  private current = 0;

  constructor(tokens: RenderCondToken[], scopeMap: Map<string, string>, source: string) {
    this.tokens = tokens;
    this.scopeMap = scopeMap;
    this.source = source;
  }

  compile(): string {
    const expr = this.parseOr();
    if (!this.check("eof")) {
      throw new Error(`Unexpected token "${this.peek().value}" in render condition "${this.source}"`);
    }
    return expr;
  }

  private parseOr(): string {
    let expr = this.parseAnd();
    while (this.matchSymbol("||")) {
      const rhs = this.parseAnd();
      expr = `(${expr} || ${rhs})`;
    }
    return expr;
  }

  private parseAnd(): string {
    let expr = this.parseEquality();
    while (this.matchSymbol("&&")) {
      const rhs = this.parseEquality();
      expr = `(${expr} && ${rhs})`;
    }
    return expr;
  }

  private parseEquality(): string {
    let expr = this.parseComparison();
    while (this.matchSymbol("==") || this.matchSymbol("!=")) {
      const op = this.previous().value;
      const rhs = this.parseComparison();
      expr = `(${expr} ${op} ${rhs})`;
    }
    return expr;
  }

  private parseComparison(): string {
    let expr = this.parseTerm();
    while (
      this.matchSymbol("<") ||
      this.matchSymbol("<=") ||
      this.matchSymbol(">") ||
      this.matchSymbol(">=")
    ) {
      const op = this.previous().value;
      const rhs = this.parseTerm();
      expr = `(${expr} ${op} ${rhs})`;
    }
    return expr;
  }

  private parseTerm(): string {
    let expr = this.parseFactor();
    while (this.matchSymbol("+") || this.matchSymbol("-")) {
      const op = this.previous().value;
      const rhs = this.parseFactor();
      expr = `(${expr} ${op} ${rhs})`;
    }
    return expr;
  }

  private parseFactor(): string {
    let expr = this.parseUnary();
    while (this.matchSymbol("*") || this.matchSymbol("/")) {
      const op = this.previous().value;
      const rhs = this.parseUnary();
      expr = `(${expr} ${op} ${rhs})`;
    }
    return expr;
  }

  private parseUnary(): string {
    if (this.matchSymbol("!")) {
      return `(!${this.parseUnary()})`;
    }
    if (this.matchSymbol("-")) {
      return `(-${this.parseUnary()})`;
    }
    return this.parsePostfix();
  }

  private parsePostfix(): string {
    let expr = this.parsePrimary();
    while (true) {
      if (this.matchSymbol(".")) {
        const name = this.consumeIdentifier();
        expr = `(${expr}.${name})`;
        continue;
      }
      if (this.matchSymbol("[")) {
        const indexExpr = this.parseOr();
        this.consumeSymbol("]");
        expr = `(${expr}[${indexExpr}])`;
        continue;
      }
      break;
    }
    return expr;
  }

  private parsePrimary(): string {
    if (this.matchType("number")) {
      return this.previous().value;
    }
    if (this.matchType("bool")) {
      return this.previous().value;
    }
    if (this.matchType("identifier")) {
      const name = this.previous().value;
      const resolved = this.scopeMap.get(name);
      if (!resolved) {
        throw new Error(
          `Unknown identifier "${name}" in render condition "{#if ${this.source}}". ` +
            "Declare it as a param or ~state.",
        );
      }
      return resolved;
    }
    if (this.matchSymbol("(")) {
      const expr = this.parseOr();
      this.consumeSymbol(")");
      return `(${expr})`;
    }
    throw new Error(`Invalid render condition near "${this.peek().value}" in "{#if ${this.source}}"`);
  }

  private consumeIdentifier(): string {
    if (!this.matchType("identifier")) {
      throw new Error(`Expected identifier in render condition "{#if ${this.source}}"`);
    }
    return this.previous().value;
  }

  private matchType(type: RenderCondTokenType): boolean {
    if (this.check(type)) {
      this.advance();
      return true;
    }
    return false;
  }

  private matchSymbol(symbol: string): boolean {
    if (this.peek().type === "symbol" && this.peek().value === symbol) {
      this.advance();
      return true;
    }
    return false;
  }

  private consumeSymbol(symbol: string): void {
    if (!this.matchSymbol(symbol)) {
      throw new Error(`Expected "${symbol}" in render condition "{#if ${this.source}}"`);
    }
  }

  private check(type: RenderCondTokenType): boolean {
    return this.peek().type === type;
  }

  private advance(): RenderCondToken {
    if (!this.check("eof")) {
      this.current++;
    }
    return this.previous();
  }

  private peek(): RenderCondToken {
    return this.tokens[this.current];
  }

  private previous(): RenderCondToken {
    return this.tokens[this.current - 1];
  }
}

const REACTIVE_RUNTIME = `function __veloxCreateReactiveState(initialState) {
  const listeners = new Set();
  let queued = false;

  const flush = () => {
    queued = false;
    for (const listener of listeners) {
      listener();
    }
  };

  const queueFlush = () => {
    if (queued) {
      return;
    }
    queued = true;
    queueMicrotask(flush);
  };

  const state = new Proxy(initialState, {
    set(target, prop, value) {
      if (target[prop] === value) {
        return true;
      }
      target[prop] = value;
      queueFlush();
      return true;
    },
  });

  const set = (patch) => {
    for (const key of Object.keys(patch)) {
      state[key] = patch[key];
    }
  };

  const subscribe = (listener) => {
    listeners.add(listener);
    return () => listeners.delete(listener);
  };

  return { state, set, subscribe };
}

function __veloxBindEvents(root, eventBindings, params, state) {
  const listeners = [];

  for (const binding of eventBindings) {
    const attr = "data-vx-on-" + binding.event;
    const nodes = root.querySelectorAll("[" + attr + "]");
    for (const node of nodes) {
      const handlerName = node.getAttribute(attr);
      if (!handlerName) {
        continue;
      }
      const handler = state[handlerName] ?? params[handlerName];
      if (typeof handler !== "function") {
        continue;
      }
      const listener = (event) => handler(event, state);
      node.addEventListener(binding.event, listener);
      listeners.push({ node, event: binding.event, listener });
    }
  }

  return () => {
    for (const entry of listeners) {
      entry.node.removeEventListener(entry.event, entry.listener);
    }
  };
}`;
