import { sep } from "node:path";

export interface VeloxRouteEntry {
  path: string;
  modulePath: string;
  layoutModulePaths: string[];
  loadingModulePath: string | null;
  errorModulePath: string | null;
}

export interface VeloxRouteManifest {
  routes: VeloxRouteEntry[];
  notFoundModulePath: string | null;
}

export function collectFileRoutes(sourceRoot: string, sourceFiles: string[]): VeloxRouteManifest {
  const routes: VeloxRouteEntry[] = [];
  let notFoundModulePath: string | null = null;
  const layoutByPagesPath = new Map<string, string>();
  const loadingByPagesPath = new Map<string, string>();
  const errorByPagesPath = new Map<string, string>();
  const pageCandidates: Array<{ pagesRel: string; modulePath: string }> = [];
  const rootIsPagesDir = /(^|[\\/])pages$/.test(sourceRoot);

  for (const sourceFile of sourceFiles) {
    const rel = toWebPath(relativeToRoot(sourceRoot, sourceFile));
    if (!hasVxExtension(rel)) {
      continue;
    }
    let pagesRel = "";
    if (rel.startsWith("pages/")) {
      pagesRel = rel.slice("pages/".length, -3);
    } else if (rootIsPagesDir) {
      pagesRel = rel.slice(0, -3);
    } else {
      continue;
    }

    const modulePath = "./" + rel.slice(0, -3) + ".js";
    const baseName = pagesRel.split("/").at(-1) ?? "";
    if (baseName.endsWith(".loading")) {
      const pageKey = pagesRel.slice(0, -".loading".length);
      if (pageKey.length > 0) {
        loadingByPagesPath.set(pageKey, modulePath);
      }
      continue;
    }
    if (baseName.endsWith(".error")) {
      const pageKey = pagesRel.slice(0, -".error".length);
      if (pageKey.length > 0) {
        errorByPagesPath.set(pageKey, modulePath);
      }
      continue;
    }
    if (baseName === "_layout") {
      layoutByPagesPath.set(pagesRel, modulePath);
      continue;
    }
    if (pagesRel === "404") {
      notFoundModulePath = modulePath;
      continue;
    }
    if (baseName.startsWith("_")) {
      continue;
    }
    pageCandidates.push({ pagesRel, modulePath });
  }

  for (const page of pageCandidates) {
    const routePath = toRoutePath(page.pagesRel);
    const layoutModulePaths = collectLayoutModulePaths(page.pagesRel, layoutByPagesPath);
    routes.push({
      path: routePath,
      modulePath: page.modulePath,
      layoutModulePaths,
      loadingModulePath: loadingByPagesPath.get(page.pagesRel) ?? null,
      errorModulePath: errorByPagesPath.get(page.pagesRel) ?? null,
    });
  }

  routes.sort(compareRoutes);
  return { routes, notFoundModulePath };
}

export function emitRouterRuntimeModule(manifest: VeloxRouteManifest, options?: { hotReload?: boolean }): string {
  const hotReload = Boolean(options?.hotReload);
  const routeJson = JSON.stringify(manifest.routes, null, 2);
  const notFoundJson = manifest.notFoundModulePath ? JSON.stringify(manifest.notFoundModulePath) : "null";
  return `// Generated by Velox Router v0.5
const __velox_routes = ${routeJson};
const __velox_not_found = ${notFoundJson};
const __velox_hot_reload = ${hotReload ? "true" : "false"};

function normalizePath(pathname) {
  if (!pathname) return "/";
  const path = pathname.replace(/\\/+$/, "");
  return path === "" ? "/" : path;
}

function parseQuery(search) {
  const out = {};
  const text = (search || "").startsWith("?") ? search.slice(1) : search || "";
  if (!text) return out;
  const params = new URLSearchParams(text);
  for (const [key, value] of params.entries()) {
    if (Object.prototype.hasOwnProperty.call(out, key)) {
      const prev = out[key];
      out[key] = Array.isArray(prev) ? [...prev, value] : [prev, value];
      continue;
    }
    out[key] = value;
  }
  return out;
}

function inferArgs(fn, routeParams, extraArgs) {
  const src = String(fn);
  const match = src.match(/\\(([^)]*)\\)/);
  if (!match || !match[1].trim()) return [];
  return match[1].split(",").map((raw) => {
    const name = raw.trim();
    if (extraArgs && Object.prototype.hasOwnProperty.call(extraArgs, name)) {
      return extraArgs[name];
    }
    if (routeParams && Object.prototype.hasOwnProperty.call(routeParams, name)) {
      return routeParams[name];
    }
    const n = name.toLowerCase();
    if (/^(on|handle)/.test(n) || /click|input|change|submit|key|handler/.test(n)) {
      return () => {};
    }
    if (/items|list|rows|data|children/.test(n)) return [];
    if (/count|num|index|id|step|age|size|len|total/.test(n)) return 0;
    if (/ready|active|enabled|visible|open|loading/.test(n)) return false;
    return name;
  });
}

function matchRoute(routePath, currentPath) {
  const routeSegs = normalizePath(routePath).split("/").filter(Boolean);
  const pathSegs = normalizePath(currentPath).split("/").filter(Boolean);
  const params = {};
  let i = 0;
  let j = 0;
  while (i < routeSegs.length && j < pathSegs.length) {
    const r = routeSegs[i];
    const p = pathSegs[j];
    if (r.startsWith("*")) {
      const key = r.slice(1) || "rest";
      params[key] = pathSegs.slice(j).join("/");
      return params;
    }
    if (r.startsWith(":")) {
      params[r.slice(1)] = p;
      i += 1;
      j += 1;
      continue;
    }
    if (r !== p) return null;
    i += 1;
    j += 1;
  }
  if (i === routeSegs.length && j === pathSegs.length) return params;
  if (i === routeSegs.length - 1 && routeSegs[i].startsWith("*")) {
    const key = routeSegs[i].slice(1) || "rest";
    params[key] = pathSegs.slice(j).join("/");
    return params;
  }
  return null;
}

function findRoute(pathname) {
  for (const route of __velox_routes) {
    const params = matchRoute(route.path, pathname);
    if (params) return { route, params };
  }
  return null;
}

function pickMountableExport(moduleExports, routeParams, extraArgs) {
  for (const [name, value] of Object.entries(moduleExports)) {
    if (typeof value !== "function") continue;
    try {
      const args = inferArgs(value, routeParams, extraArgs);
      const instance = value(...args);
      if (!instance || typeof instance !== "object") continue;
      if (typeof instance.mount === "function" || typeof instance.render === "function") {
        return { name, instance };
      }
    } catch {
      // Skip non-component exports.
    }
  }
  return null;
}

function toImportPath(modulePath) {
  return __velox_hot_reload ? modulePath + "?t=" + Date.now() : modulePath;
}

function formatError(value) {
  if (value instanceof Error) {
    return value.message;
  }
  return String(value);
}

function normalizeLoadResult(result) {
  if (!result || typeof result !== "object" || Array.isArray(result)) {
    return {
      data: result ?? null,
      redirect: null,
      notFound: false,
      error: null,
    };
  }
  const redirect = typeof result.redirect === "string" ? result.redirect : null;
  const notFound = result.notFound === true;
  const error = Object.prototype.hasOwnProperty.call(result, "error") ? result.error : null;
  const data = Object.prototype.hasOwnProperty.call(result, "data") ? result.data : result;
  return {
    data,
    redirect,
    notFound,
    error,
  };
}

function deriveDataModulePath(modulePath) {
  if (!modulePath.endsWith(".js")) return null;
  return modulePath.slice(0, -3) + ".data.js";
}

async function resolveModuleData(moduleExports, modulePath, routeCtx) {
  if (typeof moduleExports.load === "function") {
    return normalizeLoadResult(await moduleExports.load(routeCtx));
  }
  const dataModulePath = deriveDataModulePath(modulePath);
  if (!dataModulePath) return normalizeLoadResult(null);
  try {
    const dataModule = await import(toImportPath(dataModulePath));
    if (typeof dataModule.load === "function") {
      return normalizeLoadResult(await dataModule.load(routeCtx));
    }
    if (typeof dataModule.default === "function") {
      return normalizeLoadResult(await dataModule.default(routeCtx));
    }
    if (Object.prototype.hasOwnProperty.call(dataModule, "default")) {
      return normalizeLoadResult(dataModule.default);
    }
  } catch {
    // Optional data module is absent or failed to load.
  }
  return normalizeLoadResult(null);
}

function toRouteContext(pathname, params) {
  return {
    params: { ...params },
    query: parseQuery(window.location.search),
    path: pathname,
    pathname,
    search: window.location.search || "",
    hash: window.location.hash || "",
    url: window.location.href,
  };
}

export function startVeloxRouter(options = {}) {
  const rootId = options.rootId || "app";
  const statusId = options.statusId || "status";
  const root = document.getElementById(rootId);
  const statusEl = document.getElementById(statusId);
  if (!root) throw new Error("Velox router root element not found: #" + rootId);

  let cleanup = null;
  const setStatus = (msg) => {
    if (statusEl) statusEl.textContent = msg;
  };

  const mountStandalone = (mountable, statusText) => {
    if (cleanup) {
      try { cleanup(); } catch {}
      cleanup = null;
    }
    if (typeof mountable.instance.mount === "function") {
      cleanup = mountable.instance.mount(root);
    } else {
      root.innerHTML = mountable.instance.render();
    }
    setStatus(statusText);
  };

  const mountNotFound = async (pathname) => {
    if (__velox_not_found) {
      try {
        const notFoundCtx = toRouteContext(pathname, {});
        const notFound = await loadInstance(__velox_not_found, {}, notFoundCtx, notFoundCtx);
        mountStandalone(notFound, "Route: 404");
        return true;
      } catch (err) {
        console.error(err);
      }
    }
    if (cleanup) {
      try { cleanup(); } catch {}
      cleanup = null;
    }
    root.innerHTML = "<pre>Route not found: " + pathname + "</pre>";
    setStatus("Route not found");
    return false;
  };

  const loadInstance = async (modulePath, routeParams, routeCtx, extraArgs) => {
    const moduleExports = await import(toImportPath(modulePath));
    const loadResult = await resolveModuleData(moduleExports, modulePath, routeCtx);
    const mergedArgs = {
      ...(extraArgs || {}),
      data: loadResult.data,
      load: loadResult,
    };
    window.__velox_exports = moduleExports;
    const mountable = pickMountableExport(moduleExports, routeParams, mergedArgs);
    if (!mountable) {
      throw new Error("No mountable export in " + modulePath);
    }
    return { ...mountable, data: loadResult.data, load: loadResult };
  };

  const renderWithLayouts = async (pageRoute, routeParams, routeCtx) => {
    const page = await loadInstance(pageRoute.modulePath, routeParams, routeCtx, routeCtx);
    if (page.load.redirect) {
      return { kind: "redirect", to: page.load.redirect };
    }
    if (page.load.notFound) {
      return { kind: "notFound" };
    }
    if (page.load.error) {
      throw new Error(formatError(page.load.error));
    }
    if (pageRoute.layoutModulePaths.length === 0) {
      mountStandalone(page, "Route: " + pageRoute.path + " | Component: " + page.name);
      return { kind: "ok" };
    }

    if (typeof page.instance.render !== "function") {
      throw new Error("Page component must expose render() when layouts are active.");
    }
    let html = page.instance.render();

    for (let i = pageRoute.layoutModulePaths.length - 1; i >= 0; i--) {
      const layoutModulePath = pageRoute.layoutModulePaths[i];
      const layoutArgs = {
        ...routeCtx,
        data: page.data,
        content: html,
        children: html,
        child: html,
        slot: html,
      };
      const layout = await loadInstance(layoutModulePath, routeParams, routeCtx, layoutArgs);
      if (typeof layout.instance.render !== "function") {
        throw new Error("Layout component must expose render().");
      }
      html = layout.instance.render();
    }

    if (cleanup) {
      try { cleanup(); } catch {}
      cleanup = null;
    }
    root.innerHTML = html;
    setStatus("Route: " + pageRoute.path + " | Layouts: " + pageRoute.layoutModulePaths.length);
    return { kind: "ok" };
  };

  const renderCurrentRoute = async () => {
    const pathname = normalizePath(window.location.pathname);
    const matched = findRoute(pathname);
    if (!matched) {
      await mountNotFound(pathname);
      return;
    }

    try {
      const routeCtx = toRouteContext(pathname, matched.params);
      if (matched.route.loadingModulePath) {
        try {
          const loading = await loadInstance(
            matched.route.loadingModulePath,
            matched.params,
            routeCtx,
            routeCtx,
          );
          mountStandalone(loading, "Loading route: " + matched.route.path);
        } catch {
          // Loading component is optional.
        }
      }
      const outcome = await renderWithLayouts(matched.route, matched.params, routeCtx);
      if (outcome.kind === "redirect") {
        const target = normalizePath(outcome.to);
        if (target !== normalizePath(window.location.pathname)) {
          navigate(target);
        }
        return;
      }
      if (outcome.kind === "notFound") {
        await mountNotFound(pathname);
        return;
      }
    } catch (err) {
      if (matched.route.errorModulePath) {
        try {
          const routeCtx = toRouteContext(pathname, matched.params);
          const errorView = await loadInstance(
            matched.route.errorModulePath,
            matched.params,
            routeCtx,
            {
              ...routeCtx,
              error: formatError(err),
            },
          );
          mountStandalone(errorView, "Route error fallback: " + matched.route.path);
          return;
        } catch (fallbackError) {
          console.error(fallbackError);
        }
      }
      console.error(err);
      root.innerHTML = "<pre>Failed to load route module: " + formatError(err) + "</pre>";
      setStatus("Route load failed");
    }
  };

  const prefetched = new Set();
  const prefetchRoute = (to) => {
    const path = normalizePath(to);
    const matched = findRoute(path);
    if (!matched) return;
    const modules = [
      matched.route.modulePath,
      ...matched.route.layoutModulePaths,
      matched.route.loadingModulePath,
      matched.route.errorModulePath,
    ].filter(Boolean);
    for (const modulePath of modules) {
      if (prefetched.has(modulePath)) continue;
      prefetched.add(modulePath);
      import(modulePath).catch(() => {
        prefetched.delete(modulePath);
      });
      const dataPath = deriveDataModulePath(modulePath);
      if (dataPath) {
        import(dataPath).catch(() => {});
      }
    }
  };

  const navigate = (to) => {
    if (window.location.pathname === to) return;
    window.history.pushState({}, "", to);
    renderCurrentRoute();
  };

  window.addEventListener("popstate", () => {
    renderCurrentRoute();
  });
  document.addEventListener("click", (event) => {
    const el = event.target;
    if (!(el instanceof Element)) return;
    const anchor = el.closest("a");
    if (!anchor) return;
    if (anchor.target === "_blank" || anchor.hasAttribute("download")) return;
    const href = anchor.getAttribute("href");
    if (!href || href.startsWith("http:") || href.startsWith("https:") || href.startsWith("mailto:")) return;
    if (!href.startsWith("/")) return;
    event.preventDefault();
    navigate(href);
  });
  const handlePrefetch = (event) => {
    const el = event.target;
    if (!(el instanceof Element)) return;
    const anchor = el.closest("a");
    if (!anchor) return;
    if (anchor.target === "_blank" || anchor.hasAttribute("download")) return;
    const href = anchor.getAttribute("href");
    if (!href || !href.startsWith("/")) return;
    prefetchRoute(href);
  };
  document.addEventListener("mouseover", handlePrefetch);
  document.addEventListener("focusin", handlePrefetch);

  if (__velox_hot_reload) {
    const eventSource = new EventSource("/__velox_reload");
    eventSource.onmessage = () => {
      renderCurrentRoute();
    };
  }

  renderCurrentRoute();
}
`;
}

export function emitRouterHtml(title: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(title)}</title>
    <style>
      body {
        margin: 0;
        font-family: ui-sans-serif, -apple-system, Segoe UI, sans-serif;
        background: #0f172a;
        color: #e2e8f0;
      }
      header {
        padding: 16px 20px;
        border-bottom: 1px solid #1e293b;
        background: #111827;
      }
      #status {
        color: #93c5fd;
        font-size: 14px;
      }
      #app {
        padding: 20px;
      }
    </style>
  </head>
  <body>
    <header>
      <strong>Velox Router</strong>
      <div id="status">Booting router...</div>
    </header>
    <main id="app"></main>
    <script type="module">
      import { startVeloxRouter } from "./__velox_router.js";
      startVeloxRouter();
    </script>
  </body>
</html>
`;
}

function collectLayoutModulePaths(pagePagesRel: string, layoutByPagesPath: Map<string, string>): string[] {
  const out: string[] = [];
  const parts = pagePagesRel.split("/");
  parts.pop();
  const prefixes: string[] = [""];
  if (parts.length > 0) {
    let running = "";
    for (const part of parts) {
      running = running ? `${running}/${part}` : part;
      prefixes.push(running);
    }
  }
  for (const prefix of prefixes) {
    const layoutKey = prefix ? `${prefix}/_layout` : "_layout";
    const modulePath = layoutByPagesPath.get(layoutKey);
    if (modulePath) {
      out.push(modulePath);
    }
  }
  return out;
}

function relativeToRoot(root: string, file: string): string {
  const normalizedRoot = root.endsWith(sep) ? root : root + sep;
  if (file.startsWith(normalizedRoot)) {
    return file.slice(normalizedRoot.length);
  }
  return file;
}

function toWebPath(value: string): string {
  return value.split(sep).join("/");
}

function hasVxExtension(pathValue: string): boolean {
  return pathValue.toLowerCase().endsWith(".vx");
}

function toRoutePath(pagesRelNoExt: string): string {
  const rawSegments = pagesRelNoExt.split("/").filter(Boolean);
  const publicSegments = rawSegments.filter((seg) => !(seg.startsWith("(") && seg.endsWith(")")));
  const segments = [...publicSegments];
  if (segments.length > 0 && segments[segments.length - 1] === "index") {
    segments.pop();
  }
  const converted = segments.map((seg) => {
    const catchAll = seg.match(/^\[\.\.\.(.+)\]$/);
    if (catchAll) {
      return "*" + catchAll[1];
    }
    const dynamic = seg.match(/^\[(.+)\]$/);
    if (dynamic) {
      return ":" + dynamic[1];
    }
    return seg;
  });
  const joined = converted.join("/");
  return joined ? "/" + joined : "/";
}

function compareRoutes(a: VeloxRouteEntry, b: VeloxRouteEntry): number {
  const sa = routeScore(a.path);
  const sb = routeScore(b.path);
  if (sa !== sb) {
    return sb - sa;
  }
  return a.path.localeCompare(b.path);
}

function routeScore(path: string): number {
  const segs = path.split("/").filter(Boolean);
  let score = segs.length * 10;
  for (const seg of segs) {
    if (seg.startsWith("*")) {
      score -= 6;
    } else if (seg.startsWith(":")) {
      score -= 2;
    } else {
      score += 2;
    }
  }
  return score;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
